-- Clean database

DROP TABLE QR IF EXISTS;
DROP TABLE CLICK IF EXISTS;
DROP TABLE SHORTURL IF EXISTS;

-- ShortURL

CREATE TABLE SHORTURL(
	HASH		VARCHAR(30) PRIMARY KEY,	-- Key
	TARGET		VARCHAR(1024),				-- Original URL
	SPONSOR		VARCHAR(1024),				-- Sponsor URL
	CREATED 	TIMESTAMP,					-- Creation date
	OWNER		VARCHAR(255),				-- User id
	MODE		INTEGER,					-- Redirect mode
	SAFE		BOOLEAN,						-- Safe target
	IP			VARCHAR(20),				-- IP
	COUNTRY		VARCHAR(50),			-- Country
	EXPIRATIONDATE DATE,				-- Expiration Date
	EXPIRATIONTIME TIME					-- Expiration Time
);

-- Click

CREATE TABLE CLICK(
    ID 			BIGINT IDENTITY,			-- KEY
	HASH 		VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES SHORTURL(HASH),	-- Foreing key
	CREATED 	TIMESTAMP,					-- Creation date
	REFERRER	VARCHAR(1024),				-- Traffic origin
	BROWSER		VARCHAR(50),				-- Browser
	PLATFORM	VARCHAR(50),				-- Platform
	IP			VARCHAR(20),				-- IP
	COUNTRY		VARCHAR(50),					-- Country
	COMESFROMQR BOOLEAN -- If the "click" comes from a QR
);

-- QR
CREATE TABLE QR (
	ID BIGINT IDENTITY PRIMARY KEY,
	SHORTURL VARCHAR(10) NOT NULL FOREIGN KEY  REFERENCES SHORTURL(HASH),
	FG VARCHAR(50) NOT NULL,
	BG VARCHAR(50) NOT NULL,
	LOGO_IMG BLOB,
	LOGO_MEDIATYPE VARCHAR(50)
);